Adding Santa Maria
defund12/defund12.org pull request #1295
Opened 2020-06-10 15:16 UTC by dalanmiller

closes #950
note: added link to issue ^

cc: @santamariagal 

![Screenshot_2020-06-10 Defund12 org(1)](https://user-images.githubusercontent.com/863286/84285756-5d92c800-ab2d-11ea-86ec-c2801ed4a7b5.png)

2020-06-10 23:22 UTC, dalanmiller commented
Thanks @ctneal91! I had forgotten that the issue wouldn't be closed _until_ after the PR is merged which is why I didn't use that immediately. 

Thanks for the reminder 💡

2020-06-11 02:42 UTC, teddywilson requested changes

2020-06-11 02:42 UTC, bingbongle commented on _emails/us/california/santamaria.md
> +subject: [\*\*\* INSERT UNIQUE SUBJECT LINE \*\*\*]
even though we're probably doing away with subject lines altogether, no need for escape characters here.

2020-06-11 12:34 UTC, teddywilson approved these changes

2020-06-11 12:35 UTC, merged